from typing import Protocol

from .directed_edge import DirectedEdge
from .bag import Bag
from .edge import Edge


class GenericGraph(Protocol):
    _adj: list[Bag[Edge] | None]

    def V(self) -> int: ...
    def E(self) -> int: ...
    def adj(self, v: int) -> Bag[Edge]: ...
    def edges(self) -> Bag[Edge]: ...


class GenericDiGraph(Protocol):
    _adj: list[Bag[DirectedEdge] | None]

    def V(self) -> int: ...
    def E(self) -> int: ...
    def adj(self, v: int) -> Bag[DirectedEdge]: ...
    def edges(self) -> Bag[DirectedEdge]: ...
    def indegree(self, v: int) -> int: ...
