---
title: "Applied Statistics -- Exercise 1"
output:
  pdf_document: default
  html_document: default
references:
- id: Verzani2014
  type: book
  title: "Using R for Introductory Statistics"
  author:
  - family: Verzani
    given: John
  issued:
    year: 2014
  publisher: CRC Press
- id: Dekking2010
  type: book
  title: "A Modern Introduction to Probability and Statistics: Understanding why and how"
  author:
  - family: Dekking
    given: F. M.
  - family: Kraaikamp
    given: C.
  - family: Lopuhaä
    given: H. P.
  - family: Meester
    given: L. E.
  issued:
    year: 2010
  publisher: Springer-Verlag
---

*For this first exercise no R-markdown will be required. Later, it will be recommended for you to write down the exercises solutions by R-markdown, especially the solutions to the problems given as home work. In the exam, only R-markdown based presentation will be accepted, unless stated differently.*

\section{Preparation}

For the theoretical part

-   Read pages 13--21 from @Dekking2010.

For the R-Part

-   Skim through pages 3--18 from @Verzani2014.

\section{Problems}

**1.** Let $E$ and $F$ be two events for which one knows that the probability that at least one of them occurs is 3/4. What is the probability that neither $E$ nor $F$ occurs? Hint: use one of DeMorgan's laws: $E^\mathrm{C} \cap F^\mathrm{C} = (E \cup F)^\mathrm{c}$.

**2.**

a)  Let $A$ and $B$ be two events in a sample space for which $P(A) = 1/3$, $P(B)=1/2$, and $P(A \cup B) = 3/4$. What is $P(A \cap B)$?

b)  Let $C$ and $D$ be two events for which one knows that $P(C)=0.1$, $P(D)=0.3$, and $P(C \cap D) = 0.05$. What is $P(C^\mathrm{C} \cap D^\mathrm{C})$?

**3.** Consider tossing a fair coin for three times.

a)  Write down the sample space $\Omega$.

Then, write down the set of outcomes and probabilities for the the events

b)  "We throw tails exactly two times",

c)  "We throw heads at least twice,

d)  "Both the first and last throws is heads",

e)  "We get no tails at all".

**4.** Consider rolling a fair die as many times until the first six will turn up. Write down the probability that

a)  it takes exactly three rolls to get the first six.

b)  you need to roll the die more than three times to get the first six.

**5.** Use R as you would use a calculator to find numeric answers to the following expressions

a)  $1 + 2(3+4)$

b)  $4^3+3^{2+1}$

c)  $\sqrt{(4+3)(2+1)}$

d)  $\frac{1+2 \cdot 3^4}{5/6-7}$

e)  $\frac{0.25-0.2}{\sqrt{0.2 \cdot (1-0.2)/100}}$
