---
title: "Applied Statistics -- Exercise 4"
output: pdf_document
---
# Problems
T=Theoretical Exercise,
R=R Exercise

## Problem 1 (T) 

Let $X$ be a continous random variable. And let $F(x)$ be the distribution function of $X$. Let $F(a)=1/5$ and $F(b)=3/5$.

(a) What is $P(a \leq X \leq b)$?

(b) What is $P(X > b)$?

(c) What is $P(X < a \vee X > b)$?

(d) What is $P(X = a)$?

## Problem 2 (T)
Consider the continuous random variable $X$ with the following probability density function
$$
f(x) = \begin{cases}
2/3 & \text{if } 0 \leq x < 1 \\
1/3 & \text{if } 1 \leq x < 2 \\
0   & \text{otherwise.} 
\end{cases}
$$

(a) Draw, with pen and paper, the probability density function of $X$, i.e. $f(x)$.

(b) Determine the expression for the distribution function $F(x)$ of $X$, and draw it.


## Problem 3 (T)
The following exercises are about cumulative distribution functions and probability distribution funcions.

a) Let $X$ be a random variable with a $\mathrm{Exp}(0.2)$ exponential distribution. Compute $P(X > 2)$.

b) Let $X$ be a random variable with a $N(0,1)$ normal distribution. Compute $P(-0.2 < X < 0.4)$. You can use the table at the end of the book. 
In this case, note that the distribution $N(0,1)$ is symmetric around 0; use this fact to your advantage when you use the table.

c) Consider the standard normal distribution, i.e. $N(0,1)$. What is the 15th percentile of this distribution?
(Note that this is equivalent to the 0.15 quantile.)

## Problem 4 (R) 

In R you can easily use several standard distributions. For instance, by using the commands 'dnorm', 'pnorm', 'qnorm', 'rnorm', you get'll an access to the density, distribution, quantile, and random number generation of the normal distribution, respectively. 

(a) Generate 10 normally distributed samples from the standard normal distribution N(0,1). Plot them in R together with  graphs of the corresponding probability density function and the distribution function.

(b) Do the same with the exponential distribution. 

## Problem 5 (R) 

(moved to Exercise 5)
